feat(phpunit): Fail the action when unit and integration tests are skipped
This should help app developers to detect that they set up unit tests but
are not executing anything anymore due to the composer script requirement

Signed-off-by: Joas Schilling <coding@schilljs.com>

diff --git a/workflow-templates/phpunit-sqlite.yml b/workflow-templates/phpunit-sqlite.yml
--- a/workflow-templates/phpunit-sqlite.yml
+++ b/workflow-templates/phpunit-sqlite.yml
@@ -119,6 +119,13 @@ jobs:
         working-directory: apps/${{ env.APP_NAME }}
         run: composer run test:integration
 
+      - name: Skipped
+        # Fail the action when neither unit nor integration tests ran
+        if: steps.check_phpunit.outcome == 'failure' && steps.check_integration.outcome == 'failure'
+        run: |
+          echo 'Neither PHPUnit nor PHPUnit integration tests are specified in composer.json scripts'
+          exit 1
+
   summary:
     permissions:
       contents: none
